[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Create and manage Kubernetes clusters on AWS using Terraform."
homepage = "https://github.com/InQuicker/kaws"
keywords = ["kubernetes", "coreos", "aws", "terraform", "infrastructure"]
license = "MIT"
name = "kaws"
readme = "README.md"
repository = "https://github.com/InQuicker/kaws"
version = "0.5.0"

[dependencies]
ansi_term = "0.9.0"
clap = "2.20.1"
env_logger = "0.4.0"
hyper = "0.10.4"
log = "0.3.6"
rustc-serialize = "0.3.22"

[dependencies.rusoto]
features = ["kms"]
version = "0.22.0"
